name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: production-deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: registry.gitlab.com/store_images/docker-images/ethereum-key-vault

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 10.8.1

      - name: Cache PNPM store
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install & Build
        run: |
          pnpm install
          pnpm lint
          pnpm build

      - name: Login to GitLab Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USER }}
          password: ${{ secrets.GITLAB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.sha }}
          build-args: |
            NODE_ENV=production

    outputs:
      image_ref: ${{ env.IMAGE }}:${{ github.sha }}

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy application over SSH
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p 22 \
              ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << EOF
            set -e
            cd ~/backend

            # Backup old .env and create new one without leading spaces
            mv .env.production .env.production.bak || true
            echo "NODE_ENV=production" > .env.production
            echo "PORT=5000" >> .env.production
            echo "LOG_LEVEL=${{ secrets.LOG_LEVEL }}" >> .env.production

            echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env.production
            echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env.production
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.production
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.production
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.production

            echo "VAULT_ENDPOINT=${{ secrets.VAULT_ENDPOINT }}" >> .env.production
            echo "VAULT_TOKEN=${{ secrets.VAULT_TOKEN }}" >> .env.production

            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.production
            echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.production
            echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.production
            echo "GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}" >> .env.production
            echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env.production
            echo "VITE_AUTH_API_URL=${{ secrets.VITE_AUTH_API_URL }}" >> .env.production

            echo "ETHEREUM_RPC_URL=${{ secrets.ETHEREUM_RPC_URL }}" >> .env.production
            echo "SUBSTRATE_RPC_URL=${{ secrets.SUBSTRATE_RPC_URL }}" >> .env.production
            echo "SUBSTRATE_SS58_PREFIX=${{ secrets.SUBSTRATE_SS58_PREFIX }}" >> .env.production

            # Authenticate & restart services
            docker login -u ${{ secrets.GITLAB_USER }} -p ${{ secrets.GITLAB_TOKEN }} registry.gitlab.com
            docker-compose -f docker-compose.backend.yml pull postgres-backend app
            docker-compose -f docker-compose.backend.yml up -d
          EOF
